name: "sync chatGPT site"

on:
  workflow_dispatch:
  schedule:
    cron: '* * * * */1'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: sync
        env:
          URL: {{ secrets.URL }}
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
          data = $(python main.py)
          echo "urls=$data" >> $GITHUB_ENV
        working-directory: ./.github/python
      - name: replace js
        run:
          data = ${{ env.urls }}
          cat ./js/index.js | sed -i "s|soul = [(.*)]|soul = [$data]|g"
      - name: "Commit files"
        run: |
          git config --local user.email "1527736751@qq.com"
          git config --local user.name "xiaoxuan6"
          git add -A
          git commit --amend -m "fix: Update index.js" || exit 0
      - name: "Push changes"
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true